# Generated by Django 4.2.4 on 2023-09-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
