# Generated by Django 4.2.4 on 2023-09-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keepapp', '0002_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.IntegerField(unique=True)),
                ('note_title', models.CharField(max_length=50)),
                ('note_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
