# Generated by Django 4.2.4 on 2023-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_id',
            field=models.IntegerField(),
        ),
    ]
