# Generated by Django 4.2.4 on 2023-09-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepapp', '0006_alter_notes_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
